-- Copy everything in this file, paste it into Supabase SQL Editor, then click Run.

create table if not exists categories (
    id bigint generated by default as identity primary key,
    name text not null unique
);

create table if not exists groups (
    id bigint generated by default as identity primary key,
    category_id bigint not null references categories(id) on delete cascade,
    name text not null,
    unique (category_id, name)
);

create table if not exists members (
    id bigint generated by default as identity primary key,
    group_id bigint not null references groups(id) on delete cascade,
    name text not null,
    email text not null unique,
    position text,
    phone text,
    created_at timestamptz not null default now()
);

create index if not exists groups_category_id_idx on groups(category_id);
create index if not exists members_group_id_idx on members(group_id);
create index if not exists members_name_idx on members(name);
create index if not exists members_email_idx on members(email);
create index if not exists members_position_idx on members(position);

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'categories_name_key'
    ) then
        alter table categories add constraint categories_name_key unique (name);
    end if;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'groups_category_id_name_key'
    ) then
        alter table groups add constraint groups_category_id_name_key unique (category_id, name);
    end if;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'members_email_key'
    ) then
        alter table members add constraint members_email_key unique (email);
    end if;
end $$;

alter table categories enable row level security;
alter table groups enable row level security;
alter table members enable row level security;

drop policy if exists "Allow public read categories" on categories;
drop policy if exists "Allow public read groups" on groups;
drop policy if exists "Allow public read members" on members;

create policy "Allow public read categories"
on categories
for select
to anon
using (true);

create policy "Allow public read groups"
on groups
for select
to anon
using (true);

create policy "Allow public read members"
on members
for select
to anon
using (true);

insert into categories (name)
select seed.name
from (
    values
        ('Council Board'),
        ('Secretariat'),
        ('Committee'),
        ('MMM Members')
) as seed(name)
where not exists (
    select 1
    from categories
    where categories.name = seed.name
);

insert into groups (category_id, name)
select categories.id, seed.name
from (
    values
        ('Council Board', 'Chairman'),
        ('Council Board', 'Government Representative'),
        ('Council Board', 'Media Company Representative'),
        ('Council Board', 'Media Practitioner'),
        ('Council Board', 'Public Representative'),
        ('Council Board', 'Board Members Appointed'),
        ('Secretariat', 'Secretariat'),
        ('Committee', 'Law Reform & Media Literacy'),
        ('Committee', 'Media Sustainability & Professional Development'),
        ('Committee', 'Funding & Council Development'),
        ('Committee', 'Code of Conduct & Complaints'),
        ('MMM Members', 'MMM Members')
) as seed(category_name, name)
join categories on categories.name = seed.category_name
where not exists (
    select 1
    from groups existing_groups
    where existing_groups.category_id = categories.id
    and existing_groups.name = seed.name
);

create table if not exists email_records (
    id uuid primary key,
    provider_email_id text,
    email text not null,
    subject text not null default '',
    recipient_name text not null default '',
    recipient_type text not null default '',
    category text not null default '',
    group_name text not null default '',
    markdown text not null default '',
    button_text text not null default '',
    button_link text not null default '',
    html text not null default '',
    status text not null default 'sent',
    sent_at timestamptz,
    delivered_at timestamptz,
    opened_at timestamptz,
    bounced_at timestamptz,
    failed_at timestamptz,
    bounce jsonb,
    error jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists email_records_email_idx on email_records(email);
create index if not exists email_records_status_idx on email_records(status);
create index if not exists email_records_created_at_idx on email_records(created_at desc);
create index if not exists email_records_provider_email_id_idx on email_records(provider_email_id);

create table if not exists processed_webhook_ids (
    id text primary key,
    created_at timestamptz not null default now()
);

create table if not exists webhook_events (
    id uuid primary key default gen_random_uuid(),
    svix_id text unique,
    type text not null default '',
    provider_email_id text,
    recipients jsonb not null default '[]'::jsonb,
    subject text not null default '',
    received_at timestamptz not null default now()
);

create index if not exists webhook_events_received_at_idx on webhook_events(received_at desc);

create table if not exists campaign_drafts (
    id uuid primary key,
    campaign jsonb not null default '{}'::jsonb,
    summary jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists campaign_drafts_updated_at_idx on campaign_drafts(updated_at desc);

create table if not exists scheduled_campaigns (
    id uuid primary key,
    status text not null default 'scheduled',
    campaign jsonb not null default '{}'::jsonb,
    summary jsonb not null default '{}'::jsonb,
    scheduled_at timestamptz not null,
    sent_at timestamptz,
    results jsonb,
    error text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists scheduled_campaigns_status_idx on scheduled_campaigns(status);
create index if not exists scheduled_campaigns_scheduled_at_idx on scheduled_campaigns(scheduled_at);

alter table email_records enable row level security;
alter table processed_webhook_ids enable row level security;
alter table webhook_events enable row level security;
alter table campaign_drafts enable row level security;
alter table scheduled_campaigns enable row level security;

-- These production tables are written through the Express backend with SUPABASE_SERVICE_ROLE_KEY.
-- Do not add public anon policies for these tables unless you also add real admin auth.
