create table if not exists categories (
    id bigint generated by default as identity primary key,
    name text not null unique
);

create table if not exists groups (
    id bigint generated by default as identity primary key,
    category_id bigint not null references categories(id) on delete cascade,
    name text not null,
    unique (category_id, name)
);

create table if not exists members (
    id bigint generated by default as identity primary key,
    group_id bigint not null references groups(id) on delete cascade,
    name text not null,
    email text not null unique,
    position text,
    phone text,
    created_at timestamptz not null default now()
);

create index if not exists groups_category_id_idx on groups(category_id);
create index if not exists members_group_id_idx on members(group_id);
create index if not exists members_name_idx on members(name);
create index if not exists members_email_idx on members(email);
create index if not exists members_position_idx on members(position);

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'categories_name_key'
    ) then
        alter table categories add constraint categories_name_key unique (name);
    end if;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'groups_category_id_name_key'
    ) then
        alter table groups add constraint groups_category_id_name_key unique (category_id, name);
    end if;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'members_email_key'
    ) then
        alter table members add constraint members_email_key unique (email);
    end if;
end $$;

alter table categories enable row level security;
alter table groups enable row level security;
alter table members enable row level security;

drop policy if exists "Allow public read categories" on categories;
drop policy if exists "Allow public read groups" on groups;
drop policy if exists "Allow public read members" on members;

create policy "Allow public read categories"
on categories
for select
to anon
using (true);

create policy "Allow public read groups"
on groups
for select
to anon
using (true);

create policy "Allow public read members"
on members
for select
to anon
using (true);

insert into categories (name)
select seed.name
from (
    values
        ('Council Board'),
        ('Secretariat'),
        ('Committee'),
        ('MMM Members')
) as seed(name)
where not exists (
    select 1
    from categories
    where categories.name = seed.name
);

insert into groups (category_id, name)
select categories.id, seed.name
from (
    values
        ('Council Board', 'Chairman'),
        ('Council Board', 'Government Representative'),
        ('Council Board', 'Media Company Representative'),
        ('Council Board', 'Media Practitioner'),
        ('Council Board', 'Public Representative'),
        ('Council Board', 'Board Members Appointed'),
        ('Secretariat', 'Secretariat'),
        ('Committee', 'Law Reform & Media Literacy'),
        ('Committee', 'Media Sustainability & Professional Development'),
        ('Committee', 'Funding & Council Development'),
        ('Committee', 'Code of Conduct & Complaints'),
        ('MMM Members', 'MMM Members')
) as seed(category_name, name)
join categories on categories.name = seed.category_name
where not exists (
    select 1
    from groups existing_groups
    where existing_groups.category_id = categories.id
    and existing_groups.name = seed.name
);
